version: "3"
services:
    app:
        build:
            context: .
            dockerfile: ./Dockerfile
        container_name: bargaingrub
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html
    db:
        build:
            context: .
            dockerfile: ./Dockerfile-db
        container_name: bargaingrub-db
        environment:
            MYSQL_ROOT_PASSWORD: "root"